##
# Dependencies
##
brew 'coreutils' # GNU core utilities
brew 'cmake'
brew 'curl'
brew 'git'
brew 'fzf' # Fast fuzzy finder
brew 'lazygit'
brew 'libpq'
brew 'luarocks'
brew 'mas' # Mac App Store CLI
brew 'mise' # Tool version manager
brew 'neovim'
brew 'overmind'
brew 'postgresql@16', restart_service: :changed
brew 'rcm' # Dotfile management
brew 'ripgrep'

##
# Utilities
##
brew 'jandedobbeleer/oh-my-posh/oh-my-posh' # Easier zsh prompt customization
